# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_logged_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
