# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0002_auto_20180717_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, to='djangobin.Tag'),
        ),
    ]
